name: Update RVDSS Data

on:
  workflow_dispatch:
  schedule:
    # Updates are ~3pm EDT (UTC-4 or UTC-5)
    # So 21:00 UTC for safety
    - cron: '0 21 * * THU'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Download latest data
        run: python src/rvdss_update.py

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update rvdss data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
